services:
  redis:
    image: redis:7-alpine
    container_name: autotrading-redis
    ports:
      - "6380:6379"

  api:
    build: .
    container_name: autotrading-api
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
    volumes:
      - .:/app

  worker_1:
    # 주문 요청 및 주문 상태 조회(1차 워커)
    build: .
    container_name: autotrading-worker-1
    depends_on:
      - redis
    env_file:
      - .env
    command: >
      celery -A app.worker.celery_app.celery_app worker
      --loglevel=info
      --concurrency=1
      --hostname=worker1@%h
      -Q orders.submit
    volumes:
      - .:/app

  worker_2:
    # 주문 상태 추적 및 최종 상태 업데이트(2차 워커)
    build: .
    container_name: autotrading-worker-2
    depends_on:
      - redis
    env_file:
      - .env
    command: >
      celery -A app.worker.celery_app.celery_app worker
      --loglevel=info
      --concurrency=1
      --hostname=worker2@%h
      -Q orders.track
    volumes:
      - .:/app